brew "mas"
brew "coreutils"
brew "gnu-sed"
brew "yarn"
brew "direnv"
brew "git"
brew "jq"
brew "tldr"

cask "adguard"
cask "appcleaner"
cask "betterzip"
cask "docker"
cask "google-chrome"
cask "slack"
cask "suspicious-package"
cask "tableplus"
cask "tresorit"
cask "visual-studio-code"
cask "iterm2"
cask "signal"

cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"

mas "Moom", id: 419330170
